# This is a config for E2B sandbox template.
# You can use 'template_id' (8fwe9bb2ygdmk8atde2t) or 'template_name (docs) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='docs')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'docs' })

dockerfile = "e2b.Dockerfile"
template_name = "docs"
template_id = "8fwe9bb2ygdmk8atde2t"
